# name: github variables
# on: push
# jobs:
#   # Create release branch for the week
#   branch:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Format the date of next Tuesday
#         id: tuesday
#         run: echo "abbr=$(date '+tuesday%y%m%d')" >> $GITHUB_ENV

#       - name: Read exported variable
#         run: |
#           echo "$abbr"
#           echo "${{ env.abbr }}"

#       - name: Create a branch with next tuesday's date
#         run: echo "{{ env.abbr }}"

name: elastic
on: push
jobs:
  branch:
    runs-on: ubuntu-latest
    env:
      VERSION: ""
    steps:
      - name: Check-out repo
        uses: actions/checkout@v2
      # - name: Get branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: branch_name
      - name: Build and tag docker image
        shell: bash
        run: |
          echo "VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          export "VERSION=$(git rev-parse --short "$GITHUB_SHA")"
          echo "And the version is: ${{ env.VERSION }}"
      # - name: Push image to registry

      - name: Run system tests
        timeout-minutes: 60
        env:
          VER: ${{ env.VERSION }}
          PARALLELEXECUTION: 10
          BASEURL: https://system-test-peach.us.qlik-stage.com
          AUTHURL: https://sta-kube.developer.qlikcloud.com/oidc
          SUITE: OPERATIONAL
        run: |
          echo "Run tests on: ${{ env.VERSION }}"
